runtime: php55
api_version: 1
instance_class: F4_1G
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 2
  max_instances: 50
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50
handlers:
 - url: /aliexpress.*
   script: index3.php